[phases.setup]
nixPkgs = ["python311", "pango", "glib", "cairo", "gdk-pixbuf", "harfbuzz", "fontconfig", "freetype"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port 8080"
